// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#include "Robot.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"
#include "ctre/Phoenix.h"
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
std::shared_ptr<WPI_TalonSRX> RobotMap::intakeleftWheel;
std::shared_ptr<WPI_TalonSRX> RobotMap::intakerightWheel;
std::shared_ptr<frc::Solenoid> RobotMap::pneumaticGrabwheelSolenoid1;
std::shared_ptr<frc::Solenoid> RobotMap::pneumaticGrabwheelSolenoid2;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    frc::LiveWindow *lw = frc::LiveWindow::GetInstance();

    intakeleftWheel.reset(new WPI_TalonSRX(0));
    
    
    intakerightWheel.reset(new WPI_TalonSRX(1));
    
    
    pneumaticGrabwheelSolenoid1.reset(new frc::Solenoid(0, 0));
    lw->AddActuator("PneumaticGrab", "wheelSolenoid1", pneumaticGrabwheelSolenoid1);
    
    pneumaticGrabwheelSolenoid2.reset(new frc::Solenoid(0, 1));
    lw->AddActuator("PneumaticGrab", "wheelSolenoid2", pneumaticGrabwheelSolenoid2);
    

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
